[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-level debug --access-logfile - --error-logfile -"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
